const userActionTypes = {
  AUTHENTICATE_USER_PENDING: "user/AUTHENTICATE_USER_PENDING",
  AUTHENTICATE_USER_FULFILLED: "user/AUTHENTICATE_USER_FULFILLED",
  AUTHENTICATE_USER_REJECTED: "user/AUTHENTICATE_USER_REJECTED",

  EMAIL_LOGIN_PENDING: "user/EMAIL_LOGIN_PENDING",
  EMAIL_REGISTER_PENDING: "user/EMAIL_REGISTER_PENDING",

  LOGOUT_PENDING: "user/LOGOUT_PENDING",
  LOGOUT_FULFILLED: "user/LOGOUT_FULFILLED",
  LOGOUT_REJECTED: "user/LOGOUT_REJECTED",
};

export default userActionTypes;
